version: '3.9'

services:
  proxy:
    build:
      context: ../
      dockerfile: services/nginx/Dockerfile
    ports:
      - 80:80
      - 8080:8080
      - 8081:8081
      - 443:443
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      BACK_PROXY_PASS: ${BACK_PROXY_PASS:-http://backend:4000}
      FRONT_PROXY_PASS: ${FRONT_PROXY_PASS:-http://frontend:3000}
      SERVER_NAME: ${SERVER_NAME:-explorer.glitchd.network}
    restart: always
    container_name: proxy
